
services:
  api:
    image: nigmata/pokedexapi:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: final
    ports:
      - "8000:8000"
    environment:
      - ENV=production
