name: Docker Build & Push Multistage

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Docker tag based on branch
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "tag=staging" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/pokedexapi:${{ steps.vars.outputs.tag }} -f docker/Dockerfile .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/pokedexapi:${{ steps.vars.outputs.tag }}
