name: Docker Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: vars
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Show extracted version
        run: echo "Version is ${{ steps.vars.outputs.version }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/pokedexapi:${{ steps.vars.outputs.version }} -f docker/Dockerfile .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/pokedexapi:${{ steps.vars.outputs.version }}
